apiVersion: apps/v1
kind: Deployment
metadata:
  name: command-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: command-api
  template:
    metadata:
      labels:
        app: command-api
    spec:
      containers:
      - name: command-api
        image: healthmed.azurecr.io/healthmed/healthmed.commandapi:latest
        ports:
        - containerPort: 8080
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Production
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health/live
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: command-api
spec:
  selector:
    app: command-api
  ports:
    - port: 8080
      targetPort: 8080
  type: ClusterIP
